### ISSUE TITLE
Creation of article & footer via javascript, is it needed here ?

### ISSUE THREAD

**Issue by kcak11** [remy/mit-license#1270]
https://github.com/remy/mit-license/blob/7ffadd7eec60d5b636cdc81eb2e74d2976d613c5/LICENSE.html#L34

is the creation of article and footer needed via JS here. This seemed to me as unnecessary hence reported.

`<script>document.createElement('article');document.createElement('footer');</script>`

The created article and footer are nowhere used in the page because as such there is no reference to these. Hence wondering if they actually serve a real purpose.

@remy ??

**Comment by Krinkle** [comment]
@kcak11 Older versions of Internet Explorer do not support the modern HTML5 element names, suchu as "article" and "footer". In addition to not recognising them by default, it also does not allow these elements to be styled with CSS.

The standard behaviour for browsers now is not (for future compatibility) allow styling of any and all element name, including ones it does not know about yet.

Luckily, there is a trick you can do with Internet Explorer, which is to create the element in JavaScript, before it appears in your HTML or CSS. When that is the case, the rendering of stylesheet starts to work.

The element created by this JavaScript code is not used, and that is intentional.

This technique is known as the "html5 shim". Look it up if you're interested in learning more!

**Comment by kcak11** [comment]
Thanks @Krinkle, guess I missed that point.
